name: simple_github_search_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  pedantic_mono: any
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  generate: true
