name: Flutter Android CI

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "android/**"
  pull_request:
    branches:
      - master
      - develop
    paths:
      - "android/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
