name: Flutter Web CI

on:
  push:
    branches:
      - master
      - release
    paths:
      - "web/**"
  pull_request:
    branches:
      - master
      - release
    paths:
      - "web/**"

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter build web --release
