name: Flutter CI

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      # 環境構築
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true
      - run: flutter --version

      # パッケージのインストール
      - run: flutter pub get
      - run: git diff --name-only --exit-code

      # スペルチェック
      - uses: streetsidesoftware/cspell-action@v5
        with:
          config: cspell.json
          files: "**"

      # markdownlint
      - uses: DavidAnson/markdownlint-cli2-action@v15

      # prettier
      - uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: '--check --write "{**/*,*}.{json,yaml,yml,md,html,css}"'

      # ジェネレータの出力がコミットに含まれているかチェック
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: git diff --name-only --exit-code
      - run: flutter gen-l10n
      - run: git diff --name-only --exit-code

      # テスト
      # https://github.com/dart-lang/dart_style/issues/864#issuecomment-1233176900
      # ignore: *.freezed.dart, *.g.dart, *.gr.dart *.mocks.dart
      - run: dart format $(find lib -name "*.dart" -not \( -name "*.freezed.dart" -o -name "*.g.dart" -o -name "*.gr.dart" -o -name "*.mocks.dart" \) ) --set-exit-if-changed -l 120
      - run: dart format $(find test -name "*.dart" -not \( -name "*.freezed.dart" -o -name "*.g.dart" -o -name "*.gr.dart" -o -name "*.mocks.dart" \) ) --set-exit-if-changed -l 120
      - run: flutter analyze --no-fatal-infos

      - run: flutter test --exclude-tags github_api_test,golden
